---
# tasks file for httpd
- name: Installing and configuring httpd
  yum:
    name: httpd
    state: present
    update_cache: yes

- name: configuraion httpd
  copy:
    src: httpd/files/index.html
    dest: /var/www/html/
    owner: root
    group: root
    mode: '0644'   
